### ISSUE TITLE
Have a local cache for past scrobbles (per-user)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [renaudbedard/scrobblemapper#4]
```
No use downloading everything everytime, if there's a local store, the app 
could download only the latest scrobbles and thus make the updates much faster.
```

Original issue reported on code.google.com by `renaud.b...@gmail.com` on 21 Jul 2010 at 9:35

**Comment by renaudbedard** [comment]
In version 3.0, if you import a scrobble collection from an XML/JSON file you've exported beforehand, only the new weeks (which are not present from the XML/JSON file) are fetched from Last.fm.
